// AUTH
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const AUTH_LOADING = 'AUTH_LOADING';

//USERS
export const LIST_USERS = 'LIST_USERS';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const END_LOADING_USER = 'END_LOADING_USER';
export const START_LOADING_USER = 'START_LOADING_USER';
export const PROFILE = 'PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const EDIT_PROFILE = 'EDIT_PROFILE';

//products
export const LIST_PRODUCTS = 'LIST_PRODUCTS';
export const ONE_PRODUCT = 'LIST_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const END_LOADING_PRODUCT = 'END_LOADING_PRODUCT';
export const START_LOADING_PRODUCT = 'START_LOADING_PRODUCT';
export const ONE_PRODUCT_LOADING = 'ONE_PRODUCT_LOADING';
export const ONE_PRODUCT_END_LOADING = 'ONE_PRODUCT_END_LOADING';

//category 
export const LIST_CATEGORIES = 'LIST_CATEGORIES';
export const ONE_CATEGORY = 'LIST_CATEGORYS';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const END_LOADING_CATEGORY = 'END_LOADING_CATEGORY';
export const START_LOADING_CATEGORY = 'START_LOADING_CATEGORY';
export const ONE_CATEGORY_LOADING = 'ONE_CATEGORY_LOADING';
export const ONE_CATEGORY_END_LOADING = 'ONE_CATEGORY_END_LOADING';

//Projects
export const LIST_PROJECTS = 'LIST_PROJECTS';
export const ONE_PROJECT = 'LIST_PROJECTS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const END_LOADING_PROJECT = 'END_LOADING_PROJECT';
export const START_LOADING_PROJECT = 'START_LOADING_PROJECT';
export const ONE_PROJECT_LOADING = 'ONE_PROJECT_LOADING';
export const ONE_PROJECT_END_LOADING = 'ONE_PROJECT_END_LOADING';

//Blog
export const LIST_BLOGS = 'LIST_BLOGS';
export const ONE_BLOG = 'LIST_BLOGS';
export const ONE_BLOG_LOADING = 'ONE_BLOG_LOADING';
export const ONE_BLOG_END_LOADING = 'ONE_BLOG_END_LOADING';
export const END_LOADING_BLOG = 'END_LOADING_BLOG';
export const START_LOADING_BLOG = 'START_LOADING_BLOG';

//Instagram
export const LIST_INSTAGRAMS = 'LIST_INSTAGRAMS';
export const ONE_INSTAGRAM = 'LIST_INSTAGRAMS';
export const ONE_INSTAGRAM_LOADING = 'ONE_INSTAGRAM_LOADING';
export const ONE_INSTAGRAM_END_LOADING = 'ONE_INSTAGRAM_END_LOADING';
export const END_LOADING_INSTAGRAM = 'END_LOADING_INSTAGRAM';
export const START_LOADING_INSTAGRAM = 'START_LOADING_INSTAGRAM';

//Shop
export const LIST_SHOPS = 'LIST_SHOPS';
export const END_LOADING_SHOP = 'END_LOADING_SHOP';
export const START_LOADING_SHOP = 'START_LOADING_SHOP';

//Slider
export const LIST_SLIDERS = 'LIST_SLIDERS';
export const END_LOADING_SLIDER = 'END_LOADING_SLIDER';
export const START_LOADING_SLIDER = 'START_LOADING_SLIDER';

